### ISSUE TITLE
Where is "Joystick.h"

### ISSUE THREAD

**Issue by vgegok** [pepijndevos/spacefox#3]
I try This lib, But it doesn't work：
[arduino-JOYSTICK](https://github.com/gmarty2000-ARDUINO/arduino-JOYSTICK)

**Comment by vgegok** [comment]
https://github.com/MHeironimus/ArduinoJoystickLibrary
Is't this?

**Comment by pepijndevos** [comment]
Yes the latter one looks like the correct one. I'm away from home at the moment, but if that works for you, I'd wlecome a PR to update the readme to mention this.

**Comment by vgegok** [comment]
Yes. I tested the latter one,It’s working!
Thanks for your reply! I will close this issue!
