### ISSUE TITLE
Load cell instead of potentiometers?

### ISSUE THREAD

**Issue by bob-u** [pepijndevos/spacefox#4]
What do you think about using strain sensors instead of potentiometers? I think in such case stewart platform may work similar to IBM eraser mouse (aka trackpoint) only with 6 DOF.

![image](https://user-images.githubusercontent.com/61708771/229403018-9a7d5b93-537f-4fb7-9359-f4aeba375628.png)

**Comment by pepijndevos** [comment]
Interesting concept! I toyed with several ideas, and the trouble with most of them was either price or construction.
Where would you obtain suitable strain gauges and how would you construct the device?

**Comment by bob-u** [comment]
I think base and top, with necessary cutouts, could be made by PCBway or JLCPCB.  To measure force, stick-on strain gauges, two per leg, in Half-bridge configuration II (based on https://www.transducertechniques.com/wheatstone-bridge.aspx) connected to 3 HX711  (2ch each, 80sps max) amplifiers.  Both can be purchased from Ali or Amazon although I do not know how well they would work in this configuration.  Aluminum standoffs from Aliexpress (https://www.aliexpress.us/item/3256803251548057.html) can be used for legs.

$12 for PCB (set of 10), $5 HX711,$5 legs, $10 strain gauges so much more than potentiometers.  I suppose the advantages could be reaction time, longevity, precision (maybe) and smaller size.

EDIT: perhaps a better way would be to 3D print whole 6DOF rigid structure and affix strain gauges to it.  Few such structures are mentioned in this old paper: https://www.collectionscanada.gc.ca/obj/s4/f2/dsk2/tape17/PQDD_0020/MQ37577.pdf

**Comment by pepijndevos** [comment]
Yes the potential of being able to make such a device out of a single 3D print and some Sparkfun load cell amplifiers would make it very accessible. Indeed a challenge is not to make it more expensive than an actual 3dconexxion device.

**Comment by bob-u** [comment]
I agree.  I like the simplicity and low cost of potentiometers.
